const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "265994565557"
const SESSION_ID = "PRABATH-MD~1Vx1EaCS#oMeggQqOaltHnu5wuVyN9SVmkjpSsDhyOlrNzNS4uUQ"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
